lib/vmpooler/api.rb
This should make the code cleaner; things other than a template name will be used in the POST interface.
=> Rename 'template'/'count' to 'key'/'value'

lib/vmpooler/api.rb, lib/vmpooler/public/dashboard.css, lib/vmpooler/public/lib/stats-vmpooler-numbers.js
This PR includes the following changes:
- everything at the /dashboard/stats/vmpooler/numbers API endpoint has
been moved to /status, and stats-vmpooler-numbers.js is now looking to
/status for it's metrics
- added '.extra'-classed metrics to stats-vmpooler-numbers.js to pull
in daily clone totals, average clone time, etc.
- dashboard.css includes an @media query to display the extra metrics
if the dashboard's max-width exceeds 1500px
=> Extend dashboard stats

lib/vmpooler/api.rb
These changes are to match the status endpoints JSON payload. This also
introduces both clone timings and information on total clones. The field
"day" is renamed to "date" to accomodate when from/to will include
times.
=> (QENG-1873) Match status endpoint

lib/vmpooler/api.rb
When a redis key does not exist for a single-day summary, the
total_clones_per_day array has a length of 1 with a single value of 0.
This gets past an initial check of array length, but is then reduced to
a value of 0, which is then used as the denominator of an average
calculation. The result of this calculation is NaN and later causes
JSON.pretty_generate to raise an exception.
This also includes a check on the min_max_clone_times array, because
[].minmax returns [nil, nil].
=> (maint) Fix Divide by 0 Bug

lib/vmpooler/pool_manager.rb
- Store template (pool) along with hostname in Redis metric data
- Track VM boot (pending -> ready) duration
To be consumed and reported by API endpoints in a future PR.
=> More granular metrics

lib/vmpooler/api/v1.rb
This commit also consolidates the 'get_boot_metrics' and
'get_clone_metrics' methods into a single parameterized
'get_task_metrics' method.
=> /summary per-pool metrics

lib/vmpooler/api/v1.rb
This cuts down on render-time for the /api/v1/summary endpoint drastically.
=> Use $redis.hgetall rather than hget in a loop

README.md
Add documentation to the README file for the /summary end point,
including how to call with and without parameters as well as the
resulting JSON responses.
=> (QENG-1899) Add documentation for /summary

README.md, lib/vmpooler/api/v1.rb
=> (QENG-1905) Adding VM-tagging support via PUT /vm/:hostname endpoint

lib/vmpooler.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/janitor.rb, lib/vmpooler/pool_manager.rb, vmpooler, vmpooler.yaml.example
- Store VM 'checkout' and 'destroy' timestamps in Redis VM metadata object
- Do not destroy said object upon VM destruction
- Implement a Vmpooler::Janitor worker thread which compares the 'destroy' timestamp with a configurable redis['data_ttl'] option; destroy metadata object if TTL is exceeded
=> (QENG-2057) Historic Redis VM metadata

lib/vmpooler/api/v1.rb
This reduces a Redis query, as well as allowing destroyed VM metadata to still be queried.
=> Use 'checkout' time to calculate 'running' time

lib/vmpooler.rb, lib/vmpooler/api.rb, lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/janitor.rb, lib/vmpooler/pool_manager.rb, vmpooler
Prior to this commit, several pieces of vmpooler performed configuration
and initialization steps within 'initialize'. This made it difficult to
pass in mock objects for testing purposes.
This commit performs a single configuration and passes the results to
the various pieces of vmpooler.
=> (QENG-1906) Refactor initialize to allow config passing

lib/vmpooler/janitor.rb, spec/spec_helper.rb, spec/vmpooler/janitor_spec.rb
This adds tests for Janitor, verifying it deletes stale VMs.
**NOTE: THIS IS DEPENDENT ON PR #77**
=> (QENG-1906) Add spec tests for Janitor

vmpooler
This is a quick patch to solve the issue of events no longer reporting to graphite. This was due to an improper use of `defined?`.
=> Remove defined? when checking configuration for graphite server.

lib/vmpooler/pool_manager.rb, spec/vmpooler/pool_manager_spec.rb
This commit breaks apart the method check_pending_vm in to three,
smaller methods that are easier to test. There are no functionality
changes or bug fixes.
This adds spec tests for the overall functionality that was
check_pending_vm.
=> (QENG-1906) Break apart check_pending_vm and add spec tests

spec/vmpooler/api_spec.rb
Add spec tests for Sinatra powered Dashboard piece. This includes tests
for the homepage (/) and a nonexistent route.
=> (QENG-1906) Add specs for Dashboard and root API class

lib/vmpooler/pool_manager.rb
Prior to this commit, both `lifetime` and `running` were converted to `int`s and compared, causing the VM to be destroyed an hour AFTER the `vm_lifetime` config setting.
=> running-to-lifetime comparison should be 'greater than or equal to'

lib/vmpooler/api/v1.rb
Prior to this PR, if a VM's `lifetime` was changed via `POST /vm/:hostname`, the value pulled from Redis is evaluated as a string.  This forced it to return an integer in the endpoint output.
=> Ensure 'lifetime' val returned by GET /vm/:hostname is an int

lib/vmpooler/api.rb, lib/vmpooler/dashboard.rb, spec/vmpooler/api_spec.rb
This PR also introduces a new `Vmpooler::Dashboard` library which contains all of the Sinatra routes to dashboards (currently just the one).
=> Redirect / to /dashboard

lib/vmpooler/api.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/helpers_spec.rb
This moves the inline Helpers contained in V1.rb to their own file:
helpers.rb. In making this change, any API.settings call was removed
from the helper method itself and passed through from V1.
This also adds tests for hostname shortener and validate date string.
=> (QENG-2208) Move Sinatra Helpers to own file

spec/vmpooler/api/helpers_spec.rb
Add tests for more Helper methods. This moves line coverage to 59%,
leaving only get_task_metrics remaining.
=> (QENG-2208) Add more helper tests

README.md, lib/vmpooler/api/v1.rb
eg. 'pending', 'ready', 'running', or 'destroyed'.
```json
{
"ok": true,
"fdte9kozfk780y1": {
"template": "debian-7-x86_64",
"lifetime": 1,
"running": 0.05,
"state": "running",
"domain": "delivery.puppetlabs.net"
}
}
```
This is in favor of #99.
=> Display VM state in GET /vm/:hostname route

lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
Stored as `token:token` and `token:user`.
```
> hgetall vmpooler__vm__l2c9zpoe6cj99yq
1) "clone"
2) "2015-04-30 19:11:14 -0700"
3) "template"
4) "debian-7-x86_64"
5) "clone_time"
6) "4.68"
7) "check"
8) "2015-04-30 19:13:11 -0700"
9) "checkout"
10) "2015-04-30 19:15:12 -0700"
11) "token:token"
12) "c0hj5ho41n9lnvciws8wwkqxrl4c2954"
13) "token:user"
14) "sschneider"
15) "tag:beaker_version"
16) "2.10.0"
17) "tag:jenkins_build_url"
18) ""
19) "tag:department"
20) "unknown"
21) "tag:project"
22) "Beaker"
23) "tag:created_by"
24) "sschneider"
25) "destroy"
26) "2015-04-30 19:15:19 -0700"
```
=> Store token metadata in vmpooler__vm__ Redis hash

README.md, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/helpers_spec.rb
- Store daily tag roll-ups in vmpooler__tag__<date>
- GET /summary will display daily tag counts and roll-up
=> (QENG-2056) Create daily tag indexes, report in /summary

lib/vmpooler.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb, vmpooler.yaml.example
This PR adds regular expression-based tag-filtering functionality.  Given this configuration stanza:
````yaml
:tagfilter:
url: '(.*)\/'
````
...any 'url' tag will be truncated after the first matching '/' character.
=> (QENG-2518) Tag-filtering

lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
and a spec test for it.
Previously using the example shown in vmpooler.yaml.example was failing
to tag strings WITHOUT a '/' in them.
=> Only filter regex matches

lib/vmpooler/api/helpers.rb, lib/vmpooler/api/reroute.rb, lib/vmpooler/api/v1.rb
Bug in #107 squashed; resubmitting for review.
* moves the majority of summary-generation to helper methods
* implements `/summary/:route/:key` dynamic routes, eg.
* `/summary/tag`
* `/summary/tag/created_by`
* `/summary/tag/created_by?from=2015-06-01`
* `/summary/boot`
* `/summary/clone`
* `/summary/clone/duration?from=2015-05-29&to=2015-06-01`
* ...and so on
=> API summary rework

lib/vmpooler/api/reroute.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/vsphere_helper.rb, spec/vmpooler/api/v1_spec.rb, spec/vmpooler/pool_manager_spec.rb
This PR introduces host (VM) snapshotting support.  Example workflow:
1) Request a VM
````
$ curl -d '{"debian-7-x86_64":"1"}' --url vmpooler-dev/vm
{
"ok": true,
"debian-7-x86_64": {
"ok": true,
"hostname": "cxd6n45t1pd5s4j"
},
"domain": "delivery.puppetlabs.net"
}
````
2) Take a snapshot
````
This command will return a snapshot ID ("fjgd9l9okym8647gmjnznky5sklji0r3")
$ curl -d --url vmpooler-dev/vm/cxd6n45t1pd5s4j/snapshot
{
"ok": true,
"cxd6n45t1pd5s4j": {
"snapshot": "fjgd9l9okym8647gmjnznky5sklji0r3"
}
}
````
3) The vmpooler pooler_manager component sees the snapshot-creation task, and snapshots the VM in the background
````
[2015-05-01 12:35:02] [ ] [snapshot_manager] 'cxd6n45t1pd5s4j' is being snapshotted
[2015-05-01 12:39:04] [+] [snapshot_manager] 'cxd6n45t1pd5s4j' snapshot …
```
=> (QENG-2636) Host snapshots

lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
Note that this PR does not require checkout and destruction tokens to match.  This mimics the existing token behavior of `PUT /vm/:hostname`.  I'd like to enforce token-matching for both routes in a follow-up PR.
=> (QENG-1304) vmpooler should require an auth key for VM destruction

lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
The return values from most redis calls inform the caller of whether a
key or hash value exists. Several exists() calls can be removed in
favor of this approach.
Updated spec tests to account for a removal of exists() and ismember()
calls in API tests.
=> (MAINT) Reduce redis Calls in API

lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
**This PR is dependent on #123 being merged.**
* rename the Redis token 'timestamp' var to 'created'
* update the Redis token 'last' var when token is successfully validated
* expose the Redis token 'last' var in GET /token route
````
$ curl k -X GET -u jdoe --url https://vmpooler/api/v1/token
Enter host password for user 'jdoe':
````
````json
{
"ok": true,
"a9znth9dn01t416hrguu56ze37t790bl": {
"created": "2015-04-30 19:09:20 -0700",
"last": "never"
},
"amedivt3p21q7y1d5w7mcunukwxmkh6n": {
"created": "2015-08-19 11:36:10 -0700",
"last": "2015-08-19 12:37:40 -0700"
}
}
````
````
$ curl -k -X GET -u jdoe --url https://vmpooler/api/v1/token/amedivt3p21q7y1d5w7mcunukwxmkh6n
Enter host password for user 'jdoe':
````
````json
{
"ok": true,
"amedivt3p21q7y1d5w7mcunukwxmkh6n": {
"user": "jdoe", …
```
=> Track token use times

API.md, vmpooler.yaml.example
- `clone_target` in `vmpooler.yaml.example`
- `POST /vm/:vm/snapshot` and `POST /vm/:vm/snapshot/:snapshot`
- `/api/v1` everywhere
=> (maint) Documentation updates

lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
As we approach an "official" v1.0.0 of the API I'd like to remove some old
nested "ok" responses.  These were left in as the Beaker vmpooler
hypervisor used them, but I long-ago patched that code and I think it's
time to deprecate these.
=> (maint) Remove duplicate (nested) "ok" responses

lib/vmpooler/pool_manager.rb, spec/vmpooler/pool_manager_spec.rb
SSH should be available before a VM is moved from the 'pending' queue to
'ready'.
`check_ssh` should probably be a function in the tradition of DRY; I'm
going to hopefully follow up this PR with a `Vmpooler::Utility` library.
=> (QENG-2952) Check that SSH is available

lib/vmpooler/pool_manager.rb
An SSH check was added before moving a VM from pending to ready.
However, the result of that check did not matter and move_pending would
still be called. This moves the move_pending call to within the begin
block that holds the SSH check. If the check fails, then only
fail_pending will be called.
=> (maint) Move VM Only When SSH Check Succeeds

lib/vmpooler/pool_manager.rb, spec/vmpooler/pool_manager_spec.rb
Prior to this commit, a running VM could fail a ping check and be destroyed. This causes issues when network hiccups occur or the machine is performing a reboot.
A VM that is in a ready state will now be destroyed when handed back or it hits the lifetime TTL.
=> (MAINT) Remove Ping Check on Running VMs

API.md, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
This is deployed on `vmpooler-dev`.
````
$ curl -k -X GET --url https://vmpooler-dev.delivery.puppetlabs.net/api/v1/token/cxig75je6dzjjinbg5oxmfjup63libs5
````
````json
{
"ok": true,
"cxig75je6dzjjinbg5oxmfjup63libs5": {
"user": "sschneider",
"created": "2015-11-03 14:56:57 -0800",
"last": "2015-11-04 12:28:37 -0800",
"vms": {
"running": [
"dqs4914g2wjyy5w",
"hul7ib0ssr0f4o0"
]
}
}
}
````
=> (QENG-2995) Display associated VMs in GET /token/:token endpoint

lib/vmpooler.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb, vmpooler.yaml.example
The following pool configuration would allow a pool to be aliased in POST requests as '`centos-6-x86_64`', '`centos-6-amd64`', or '`centos-6-64`':
````yaml
- name: 'centos-6-x86_64'
alias: [ 'centos-6-amd64', 'centos-6-64' ]
template: 'templates/centos-6-x86_64'
folder: 'vmpooler/centos-6-x86_64'
datastore: 'instance1'
size: 5
````
The `alias` configuration can be either a string or an array.
Note that even when requesting an alias, the pool's `name` is returned in the JSON response:
````
$ curl -d '{"centos-6-64":"1"}' --url vmpooler/api/v1/vm
````
````json
{
"ok": true,
"centos-6-x86_64": {
"hostname": "cuna2qeahwlzji7"
},
"domain": "company.com"
}
````
=> (QENG-2807) Allow pool 'alias' names

lib/vmpooler/pool_manager.rb
This commit adds a custom guestinfo keyword and hostname variable
that allows the VMware Tools to query the hostname.
```
root@akyjym751lr8cu3:~# vmtoolsd --cmd "info-get guestinfo.hostname"
akyjym751lr8cu3
```
This should allow us some flexibility in moving away from the requirement to talk to vCenter during bootstrap of a pooler VM in order to obtain the hostname.
=> add guestinfo.hostname to VirtualMachineConfigSpecs

README.md
Add a new section to the README to reference the CLI utility for accessing
vmpooler services.
[skip ci]
=> (QA-2036) Update README for Client Utility

scripts/create_template_deltas.rb
The symbol notation for the YAML variables "server," "username," and, "password," were not working for me.  When changing them to strings the script seems to work.
=> Updated YAML config variables in create_template_deltas.rb

lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, vmpooler.yaml.example
I've found it useful to be able to specify a prefix to all created VMs.  This can help with defining autosign policy for puppet ("sign $prefix-<random string>") as well as VM organization.  This adds an optional parameter that lets the user do exactly this.
=> Added prefix parameter to the vmpooler configuration

API.md, lib/vmpooler/api/reroute.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/vsphere_helper.rb
Add an additional disk to a running VM via the vmpooler API.
````
$ curl -X POST -H X-AUTH-TOKEN:a9znth9dn01t416hrguu56ze37t790bl \
--url vmpooler.company.com/api/v1/vm/fq6qlpjlsskycq6/disk/8
````
````json
{
"ok": true,
"fq6qlpjlsskycq6": {
"disk": "+8mb"
}
}
````
Provisioning and attaching disks can take a moment, but once the task completes it will be reflected in a `GET /v1/vm/<hostname>` query:
````
$ curl --url vmpooler.company.com/api/v1/vm/fq6qlpjlsskycq6
````
````json
{
"ok": true,
"fq6qlpjlsskycq6": {
"template": "debian-7-x86_64",
"lifetime": 2,
"running": 0.08,
"state": "running",
"disk": [
"+8mb"
],
"domain": "delivery.puppetlabs.net"
}
}
=> Allow new disks to be added to running VMs via vmpooler API

API.md, Gemfile, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
Prior to this, vmpooler could partially fill requests for multiple VMs. Here we move to an algorithm that returns the entire set of requested VMs or no VMs.
/cc @puppetlabs/cinext
=> [QENG-3919] Make vmpooler checkouts be all or nothing

Gemfile, lib/vmpooler.rb, lib/vmpooler/api.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/statsd.rb, spec/spec_helper.rb, spec/vmpooler/api/v1_spec.rb, spec/vmpooler/pool_manager_spec.rb, vmpooler, vmpooler.yaml.example
Add the tracking of running, ready, and clone time for VM
Add the tracking of of successful, failed, invalid, and empty pool vm gets.
It is possible we may want to tweak this, but have validated with spec tests and pcaps.
```
vmpooler-tmp-dev.ready.debian-7-x86_64:1|c
vmpooler-tmp-dev.running.debian-7-x86_64:1|c
vmpooler-tmp-dev.checkout.invalid:1|c
vmpooler-tmp-dev.checkout.success.debian-7-x86_64:1|c
vmpooler-tmp-dev.checkout.empty:1|c
vmpooler-tmp-dev.running.debian-7-x86_64:1|c
vmpooler-tmp-dev.clone.debian-7-x86_64:12.10|ms
vmpooler-tmp-dev.ready.debian-7-x86_64:1|c
```
=> (RE-7014) add statsd support

lib/vmpooler/api/v1.rb
I've discovered a need to see the IP of a vm from vmpooler when querying the status of a vm.  This code utilizes the same TCPSocket functionality found elsewhere in the codebase to retrieve the IP from vmpooler's perspective.  This information is localized to returning information about a vm since this is where all the other in-depth information about a vm is contained and only adds to the data, does not modify existing data.  This should means that scripts and workflows currently against vmpooler shouldn't need modification to continue functioning.
=> Added IP lookup functionality for /vm/hostname

LICENSE, README.md
Prior to this commit, the README and LICENSE referenced Puppet Labs.
This commit updates those files to drop the "Labs" from these
references.
=> (maint) update README.md and LICENSE to reflect rebranding

lib/vmpooler/api/v1.rb, spec/helpers.rb, spec/vmpooler/api/v1/vm_spec.rb, vmpooler.yaml.example
At current vm_lifetime and vm_lifetime_auth are configured globally only.  This change allows that value to be set/overridden per pool.
=> (QENG-3376) Allow lifetime to be set per-pool

.travis.yml, lib/vmpooler/api/v1.rb, spec/helpers.rb, spec/vmpooler/api/v1/status_spec.rb
Prior to this the only per-pool statistics that could be extracted from the API were a list of empty pools in the "status" section of the returned results of the `/status` endpoint.
This adds a new "pools" section to the '/status' results which lists, for each
pool, the following results:
- The number of ready vms in the pool
- The number of running vms in the pool
- The number of pending vms in the pool
- The maximum size of the pool (as specified in the vmpooler configuration)
Example:
```
{
"boot": {
"duration": {
"average": 163.6,
"min": 65.49,
"max": 830.07,
"total": 247744.71000000002
},
"count": {
"total": 1514
}
"pools": {
"pool1": {
"ready":   5,
"running": 2,
"pending": 1,
"max":     15
},
"pool2": {
"ready":   0,
"running": 10,
"pending": 0,
"max:      10
}
}
}
```
**tasks**
cc …
=> [QENG-4181] Add per-pool stats to `/status` API

Gemfile, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/vsphere_helper.rb, spec/helpers.rb, spec/vmpooler/pool_manager_migration_spec.rb, spec/vmpooler/pool_manager_spec.rb, vmpooler.yaml.example
This change implements improved scheduling of pooled VMs by updating the logic used to find the least used host in a target cluster. Without this change host selection is based on VM count, which does not give an indication of VM size or current host utilization.
Additionally, this change implements a queue for migrating VMs at request time. The least used compatible host is selected for migration, which occurs transparently to the consumer, and migration is performed if required.
Without these changes vmpooler may cause uneven load distribution across a cluster of resources since the consumption of VMs is separated from scheduling.
=> Improve vmpooler scheduling logic

lib/vmpooler/pool_manager.rb, lib/vmpooler/vsphere_helper.rb
This commit updates vmpooler.migrate metric to send the pool name. Without this change the VM name is sent. Additionally, counts are added for migrate_from_#host and migrate_to_#host in order to allow tracking host migrations, and correlating them with CPU ready time changes.
=> (POOLER-44) Fix vmpooler.migrate reference

lib/vmpooler/pool_manager.rb, lib/vmpooler/vsphere_helper.rb, vmpooler.yaml.example
This commit adds retry logic and configurable delays to vsphere helper.
Without this change vmpooler instances that have large numbers of pools
can create enough connections in a short period of time to cause vcenter
issues.
=> Add retry logic with a delay for vsphere connections

Gemfile
It is much more performant than the Sinatra's built-in WEBrick.
=> Add `puma` as required gem

lib/vmpooler/public/lib/dashboard.js
Without this patch the dashboard will error-out on unfound `weekly_data` values.
=> Fix JavaScript error on nil `weekly_data`

lib/vmpooler/pool_manager.rb
This commit updates vmpooler to ensure clone errors, and other pool manager errors are raised to the parent method. Without this change vmpooler gets stuck after a connection fails during clone operations and will not attempt to clone again.
=> (POOLER-47) Send clone errors up

lib/vmpooler/pool_manager.rb
This commit updates vmpooler to clear the migrations queue at application start time. When the application is shut down it is not considerate of any activities, like migrations, in flight. The result is that when the application is started again any stale entries in vmpooler__migration will be left until manually removed, which can prevent migrations from occurring.
=> (POOLER-48) Clear migrations at application start time

Dockerfile, README.md, lib/vmpooler.rb
Built off the [jruby](https://hub.docker.com/_/jruby/) `Dockerfile`, it installs gem requirements via `bundler`, installs and runs a `redis-server`, imports the current working directory, starts `vmpooler`, and tails the logfile.
Creating a `vmpooler.yaml` configuration file in the current working directory and running the following provides a development environment:
```
docker build -t vmpooler . && docker run -p 80:4567 -it vmpooler
```
=> Containerize vmpooler

.travis.yml
Ruby 1.9.3 is end of life, and now longer bundles due to later Nokogiri 1.7.0.1
requiring Ruby 2.1 or above.  This commit removes ruby 1.9.3 from Travis
testing.
=> (maint) Remove Ruby 1.9.3 testing from Travis

.gitignore, Gemfile, vmpooler
Previously, a bundle install would not pull in gems from Gemfile.local or
~/.gemfile which are common development workflows in Puppet.  This commit
modifies the Gemfile to pull in these additional gemfiles if they exist.  This
commit also adds common files and folders to gitignore which should not be
committed to this repository.
Previously, if you ran the vpooler via ruby, pressing Ctrl-C would terminate the
Webserver however the PoolManager does not have a handler and would instead
just keep executing.  This commit adds a global Ctrl-C hook which terminates
both the api and manager threads.  This behaviour will only be enabled if the
`VMPOOLER_DEBUG` environment variable exists so that it does not affect VMPooler
when running in production environments.
=> (maint) Enhance VM Pooler developer experience

lib/vmpooler.rb, lib/vmpooler/api/helpers.rb, vmpooler.yaml.example
Previously it was difficult to do local development as VMPooler requires an LDAP
service for authentication. This commit adds a dummy authentication provider.
The provider has passes authentication if the username and password are
different, and fails if the username and password are the same.  This commit
also updates the documentation in the config YML file.
=> (POOLER-71) Add dummy authentication provider

Rakefile
Previously in commit 145ecb443f Rakefile was modified to require the Rubocop
gem however, this gem is not available on jruby systems and would throw errors.
This commit modifies the Rakefile to first detect if the Gem is available and
optionally load the rubocop rake tasks.
=> (maint) Only load rubocop rake tasks if gem is available

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Previously in check_ready_vm, if the VM is powered off, the VM is moved in
redis however the function doesn't return there, and instead then checks if the
hostname is the same, and then if TCP socket 22 is open. This is unnecessary as
we already know the VM is turned off so of course the hostname is wrong and TCP
22 is unavailable. The same applies for the VM hostname.
This commit instead returns after it is found a VM is no longer ready.  This
commit also amends the spec tests for the correct behaviour.
~~Note - This PR is blocked on PR #183 being merged~~
=> (GH-185) Remove unnecessary checks in check_ready_vm 

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Previously, the clone_vm method took various VSphere specific parameters e.g.
template folder.  However in order make VMPooler less VSphere specific this
method should just take the pool configuration and then it can determine the
appropriate settings itself.  This commit also moves the threading to a clone_vm
while the actual method which does the work is now _clone_vm as per all other
multithread worker methods in pool_manager.  This commit also updates the spec
tests appropriately.
=> (POOLER-70) Refactor clone_vm to take pool configuration object

lib/vmpooler/vsphere_helper.rb
This commit removes a duplicate increment of the metrics.connect.open count. Without this change two connections will be reported when one is made.
This should address #195
=> Remove duplicate of metrics.connect.open

lib/vmpooler/vsphere_helper.rb
This commit updates usage of global variables in vsphere_helper to be instance variables. They do not need to be global variables as brought up in issue #194. Without this change we are setting global variables when they are not needed.
=> Update usage of global variablesin vsphere_helper

lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers.rb, lib/vmpooler/providers/base.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb, spec/unit/providers/base_spec.rb, spec/unit/providers/vsphere_spec.rb
Previously all of the VM provisioning code was intertwined with the VM lifecycle
code e.g. The VSphere specific code is mixed with Redis code.  This makes it
impossible to add aditional providers or disable VSphere integration.  This
commit begins the process to refactor the VSphere code out of the lifecycle code
by introducing the concept of VM Providers.  A Provider will contain the logic/
code to manage VMs i.e. create/destroy/inquire.  Therefore the Pool Manager can
query a strict interface into one or more Providers.  Initially only a VSphere
provider will be available.
This commit adds the base class for all providers and describes the API or
contract that the Pool Manager will use to manage VMs.
VM provisioning will be handled by VM Providers.  This commit renames the use of …
=> (POOLER-70) Prepare to refactor VSphere code into a VM Provider

lib/vmpooler/vsphere_helper.rb
In commit 03ad7bfa468 the global variables for credentials was change to an
instance variable however one reference was missed.  This commit fixes this
omission.
=> (maint) Fix credentials in vsphere_helper

lib/vmpooler/vsphere_helper.rb, spec/rbvmomi_helper.rb, spec/spec_helper.rb, spec/unit/vsphere_helper_spec.rb
Previously there were no spec tests to document the behaviour of the
vsphere_helper.  This commit adds the behavioural spec tests in prepration of
the refactoring work as part of POOLER-70, the connection pooling work in
POOLER-52 and various bugs found in vsphere_helper while these spec tests were
being created.
=> (POOLER-73) Add spec tests for vsphere_helper

lib/vmpooler/logger.rb
Previously all log messages may be written to a text file, however during
development or debugging it is also useful if the log messages are written to
the console.  This commit changes the logger class to emit messages to the
console, via `puts`, if the `VMPOOLER_DEBUG` environment variable is set.
=> (maint) Emit console messages when debugging is enabled

Gemfile
Rack was updated recently and 2.x requires ruby 2.2 or above. As VMPooler should
work in older jruby, we need to be Ruby 1.9.3 compatible.  This commit pins
the rack gem to 1.x.
=> (maint) Pin rack to 1.x

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
The same method logic was being used in two places but only one was calling the method
get_cluster_host_utilization, so this refactors it to use the method for both.
The method could also return an empty array and the subsequent line would try
to .sort[0][1] which would return undefined method [] for nil:NilClass in that
case. The return value is now checked and an exception raised
=> Refactor get_cluster_host_utilization method

README.md, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb, vmpooler.yaml.example
Refactoring the vmpooler.yaml format to support multiple providers.
The second level key under :providers: is a unique key name that
represents a provider that can be referred in the pool's parameter
called provider. The code is still backward compatible to support
the :vsphere: and :dummy: keys but in reality if you have more than
one vsphere configuration you would give them a different name. For
example :vsphere-pdx: and :vsphere-bfs: and the actual provider
class would be specified as a parameter called 'provider_class'.
See tests and examples for more information.
=> Adding support for multiple vsphere providers

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
Previosuly in find_vmdks in vsphere_helper it uses the call
vmdk_datastore._connection to get the underlying connection, however this is
already available as function parameter.  This commit removes this bad code and
the associated test fixtures.
=> (GH-213) Remove use of private _connection method

lib/vmpooler/providers/vsphere.rb, spec/rbvmomi_helper.rb, spec/unit/providers/vsphere_spec.rb, vmpooler.yaml.example
This PR builds on PR #224 
Previously the vsphere provider assumed that there was one and only one
datacenter (DC) in the vsphere instance.  However this is simply not true for
many vSphere installations.  This commit:
- Adds the ability to define a vSphere datacenter at the Pool or Provider level
whereby the Pool setting takes precedence
- If no datacenter is specified the default behaviour of picking the first DC
in the vSphere instance
- Updated all tests for the new setting
- Update the vmpooler configuration file example with relevant setting name
and expected behaviour
- Fixed a bug in the rvmomi_helper whereby if no DC was found it would return
all DCs.  This is opposite behaviour of the real RBVMOMI library as it returns
nil
=> (POOLER-83) Add ability to specify a datacenter for vsphere

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates find_least_used_compatible_host method to specify
the pool name when evaluating a VM for migration. Without this change VM
migration fails with a wrong number of arguments error. Pool_manager
test references are updated to reflect the change.
=> Update find_least_used_compatible_host to specify pool

.rubocop.yml, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb, vmpooler.yaml.example
Previously the check_pool would always check the pool every 5 seconds, however
with a large number of pools, this can cause resource issues inside the
providers.  This commit:
- Introduces a dynamic check_pool period which increases during stability and
decreases when the pool is being change in an important way
- Surfaces the settings as global config defaults but can also be set on a per
pool basis
- Adds defaults to have default of 5 to 60 seconds and decay of 2.0
- Unit tests for the new behaviour
=> (GH-226) Use a dynamic pool_check loop period

Gemfile, lib/vmpooler/pool_manager.rb
Previously, a static list was used to instantiate VM Pooler Provider objects.
This commit changes the loader to instead interrogate the available clases in
the Vmpooler::PoolManager::Provider namespace and then instantiate from there.
This means class names are not case sensitive and that VM Providers can now be
dynamically loaded from other sources such as gems in the LOADPATH.  No tests
were added as this behaviour is exercised in the execute! tests already.
=> (GH-230) Dynamically load VM Providers

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Previously, if inventory failed for some reason, it would return an incomplete
set of VMs which could then cause the pool to perform off behaviours such as
fill the pool high than it should, or remove VMs which exist.  Also, if the
redis cache of VMs in a pool had a VM but it did not actually exist in the
inventory it would never be removed.
This commit:
- Immediately exits the check_pool if an error occurs during inventory
collection
- Will mark a VM as completed if it exists in Redis, but does not exist in
inventory
- Adds tests for these behaviours
=> (maint) Remove phantom VMs that are in Redis but don't exist in provider

scripts/create_template_deltas.rb
The vmpooler.yaml file has been reorganized a bit and now nests the
vsphere credentials within a "providers" class. This tweak is needed
to keep the template delta script working.
=> (maint) Update template delta script for moved vsphere credentials

lib/vmpooler/providers/vsphere.rb, spec/rbvmomi_helper.rb, spec/unit/providers/vsphere_spec.rb
This commit adds vmpooler inspection of configuration issues to host
selection. Specifically, configIssue is checked, which should allow an
issue like quickstats not being reported to be identified even when the
alarm will not trigger. Without this change a host will continue to be
used if quickstats are not reported when alarms are not triggered
because of this condition, which results in a single host being the
target for all deploys and migrations, overloading the host and causing
its VMs to have degraded performance.
=> (POOLER-89) Identify when config issue is present

Gemfile, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Previously in commit 9b0e55f the looping period was changed from a static
number to a dynamic one depending on load, however this meant that the operation
to refill a pool was slowed down somewhat.  While not a problem under normal
loads, when a pool was quickly consumed, the pool manager may not respond
quickly enough to refill the pool.  This commit:
- Changes the sleep method, to us a helper sleep method that will wakeup
periodically and evaluate other wakeup events.  This could be used later to
exit sleep loops when pooler is shutting down to stop blocking threads
- By default the wakeup_period is set to the minimum pool check loop time, thus
emulating the behaviour prior to commit 9b0e55f
- Adds tests for the behaviour
=> (GH-226) Respond quickly to VMs being consumed

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Before this change if the boottime was nil, the check_ready
loop would exit on Time.now - host['boottime'] with a TypeError
in jruby. The boottime is nil when the power is Off so moving that check
earlier should catch that bug.
=> Fix no implicit conversion to rational from nil

lib/vmpooler/api/v1.rb, spec/integration/api/v1/status_spec.rb
Built on top of POOLER-92, this should be merged after.
---
The status endpoint provides a lot of statistics. This commit extends it
by supporting a query parameter called 'view' which may contain one or
multiple comma separated names for the top-level statistics returned
in the JSON response. status is always returned.
Optional elements are capacity,queue,clone,boot,pools
Everything is returned when 'view' is not specified, which is
backwards compatible with the current behavior.
=> (POOLER-93) Extend API endpoint to provide just what is needed

README.md, Vagrantfile
This move vmpooler to my newer Vagrant box and also documents how to run directly in Vagrant using different versions of ruby.
=> Updated Vagrant box and associated docs

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
This commit updates cpu_utilization_for and memory_utilization_for to detect when quickstats are not present. Without this change a nil result is transformed to 0, which is perceived as a host that has no utilization.
=> Identify when ESXi host quickstats do not return

.travis.yml, Gemfile
This commit updates travis configuration to replace jruby 1.7.13 with 9.1.13.0. Without this change the jruby version tested is out of date and does not support features like safe_load, which affects issue #243.
=> Update jruby version for travis to 9.1.13.0

.gitignore, docs/dev-setup.md, lib/vmpooler.rb, spec/fixtures/vmpooler.yaml, spec/fixtures/vmpooler2.yaml, spec/spec_helper.rb, spec/unit/providers/vsphere_spec.rb, spec/unit/vmpooler_spec.rb
Previously, there were two ways to configure Vmpooler, either by
changing the contents of vmpooler.yaml or by assigning the raw YAML
to the VMPOOLER_CONFIG environment variable. This commit adds a new
environment variable called VMPOOLER_CONFIG_FILE that can be assigned
the name of a config file to use. Also fixes #240 by whitelisting the
Symbol class when calling YAML.safe_load in Vmpooler.config.
=> Allow user to specify a configuration file in VMPOOLER_CONFIG_FILE variable

lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit add a redis hash where there is one key per pool, and the
stored value is the last time a VM was booted e.g. the last time
a VM went from 'pending' to 'ready'. This is also displayed in the
API as lastBoot:'2018-03-23 17:43:39 +0000'. The data can then be
used by any external system, in this case our alarming system.
=> (maint) Add the last boot time for each pool

Gemfile
This commit updates nokogiri and net-ldap to versions that have fixed known vulnerabilities. Without this change vmpooler requires versions of each gem that contain known vulnerabilities.
=> (POOLER-101) Update nokogiri and net-ldap

lib/vmpooler.rb
This commit updates the method used to load a configuration file to use
YAML.load_file, which is how it was configured previously. The
capability to specify an alternate configuration file via the
VMPOOLER_CONFIG_FILE is retained, and now works as expected.
=> (POOLER-103) Fix configuration file loading

Dockerfile-aio
This commit adds a dockerfile to install vmpooler without a local redis installation. Without this change the dockerfile provided assumes a local redis instance will be running. The dockerfile with redis is retained as 'Dockerfile-aio'. Additionally, the directory '/var/log/vmpooler' is no longer created since vmpooler uses '/var/log/vmpooler.log'.
=> Add dockerfile without redis

scripts/vmpooler.service
I realized the launcher itself handles looking up the Ruby interpreter with /usr/bin/env ruby. Manually specifying an interpreter is going to try to circumvent that and isn't nearly as portable as an example service. By moving this sample script back to the generic launcher directly a user can choose to handle how /usr/bin/env looks up Ruby, whether it's with a jruby installation, rbenv, or however the user wishes.
=> Update to generic launcher

lib/vmpooler.rb, vmpooler
This commit adds options for setting redis port and password. Without this change it is not possible to specify the redis port or password.
=> Add support for setting redis port and password

.travis.yml
This commit updates ruby versions specified for use when testing in
travis.yml. Specifically, ruby 2.4.x and 2.5.x are added, while 2.2 is
updated to 2.2.10, and 2.3 is updated to 2.3.7. Additionally, jruby
testing is updated to use 9.1.17.0. Without this change we do not test
ruby 2.4.x or 2.5.x with vmpooler.
=> Update ruby versions for travis

lib/vmpooler/providers/vsphere.rb, vmpooler.yaml.example
This commit changes the vsphere connection behavior to set insecure false. Without this change insecure is always set to true when making a connection regardless of the setting provided with the provider configuration.
=> Change default vsphere connection behavior

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates pool_manager to expire a redis VM key when a clone fails. Without this change VMs that fail to clone have their metadata left forever.
=> (POOLER-31) Expire redis vm key when clone fails

.travis.yml
This commit adds jruby 9.2 to travis testing. Without this change vmpooler is not tested against jruby 9.2.
=> Add jruby 9.2 to travis testing

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
These commits reduce the number of objects looked up when finding VM folders. Additionally, object lookup methods that scan for a folder with a matching name are removed in favor of searchIndex with FindByInventoryPath. Without this change the time it takes to find VM folders is much longer and more resource intensive.
=> Reduce object lookups for finding folders

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates check_pool inventory check to prevent multiple instances from running at once. Without this change the inventory check may run in multiple threads simultaneously.
=> Do not run duplicate instances of inventory check for a pool

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates how template delta disk creation is evaluated. Without this change template deltas are created for every template on each applicatoin startup. This change updates this behavior to instead run template delta disk creation only once per template configured for a pool. Without this change it is possible to get a template to a state where the XML depth is too great to be read with default settings and the template requires a new clone to resolve.
=> Ensure template deltas are created once

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
This commit updates get_pool_vms to only return if the object is a VirtualMachine. Without this change a folder wtihin a VM target folder can be discovered and destroyed as though it were a VM.
=> (POOLER-40) Do not return folders with get_pool_vms

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
This commit updates usage of max_tries to ensure that the increment of the try value happens after evaluation of whether max_tries has been exceeded. Without this change max_tries doesn't work as advertised. Additionally, checking looks to see if try is greater than or equal to so the try count exceeding max_tries would also be detected.
=> (POOLER-124) Fix evaluation of max_tries

spec/unit/providers/vsphere_spec.rb
This commit updates a test reference to find_vm. This method has been renamed find_vm_folder, so this commit updates usage to reflect the new title and reduced arguments required. Without this change tests fail on master.
=> (MAINT) Fix test reference to find_vm

lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb
Before, the only time calculation displayed for a given VM was the
lifetime parameter. Added the time_remaining parameter which will
display time until the VM is destroyed in hours, minutes, seconds.
Additionally, updated the running parameter to display in a similar
fashion as time_remaining.
=> (POOLER-81) Add time_remaining information

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Before, we were already capturing this metric but we failed to ship
it anywhere. This ships the appropriate metric as `time_to_ready_state`
Dashboards can be created easily in grafana.
=> (POOLER-34) Ship clone request to ready time to metrics

lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb
Before, the only time calculation displayed for a given VM was the
lifetime parameter. Added the remaining parameter which will
display time until the VM is destroyed as a float.
Additionally, start_time and end_time were added to api to return
as RFC3339 based times (e.g. 2018-07-11T09:54:51-07:00).
/cc @glennsarti @johnmccabe @mattkirby
=> (POOLER-81) Add time remaining information

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This change eliminates a secondary layer of VM object retrieval when checking VM state. Check_pool gathers an inventory of known VMs and then only runs checks for pending, ready and running VMs on instances it has validated as existing in the inventory. As a result it is wasteful to run get_vm and check these objects for a second time. Where possible this checking is removed and configured to run less frequently. For VM hostname mismatch checking an option is added to allow a user to turn this off per pool or globally. Without these changes vmpooler will take significant amounts of memory when configured to run many VMs across many pools due to a large number of object lookups.
=> Eliminate duplicate VM object lookups where possible

bin/vmpooler
During a rebase the vmpooler require was mixed up and still specified
lib/vmpooler. This commit removes this as well as the rubygems
requirement. Without this change vmpooler fails to work when built
because it cannot load lib/vmpooler.
=> (maint) Fix vmpooler require in bin/vmpooler

.travis.yml
This commit removes ruby 2.2.10 from travis configuration. Without this change travis tests fail since vmpooler has dropped ruby 2.2.10 support.
=> (maint) Remove ruby 2.2.10 from travis config

lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/base.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb, spec/unit/providers/vsphere_spec.rb, vmpooler.yaml.example
This commit enables optional purging for vms and folders when they are
not configured in the vmpooler provided configuration. Base folders are
determined from folders specified in the pool configuration. Then,
anything not configured in that folder for that provider and is not a
whitelisted folder title will be destroyed. Without this change vmpooler
will leave unconfigured vms and folders behind and any vms will be left
running forever without manual intervention. Additionally, any
associated redis data will never be expired.
=> (POOLER-66) Purge vms and folders no longer configured

README.md, docs/API.md, docs/dev-setup.md, examples/vmpooler.yaml.dummy-example.aliasedpools, spec/fixtures/vmpooler.yaml, spec/fixtures/vmpooler2.yaml, spec/unit/pool_manager_spec.rb, vmpooler.yaml.dummy-example, vmpooler.yaml.example
Prior to this commit the docs and examples used 'company.com'
(a real domain). This commit changes those occurrences to
'example.com', which is a IANA-managed reserved domain.
=> (maint) change domain to example.com

CHANGELOG.md, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates destroy_vm to remove references to its mutex tracking object when destroyed. Without this change a VM that is destroyed will leave its mutex tracking object forever causing the pool manager memory footprint to increase.
=> (POOLER-128) Remove references to VM mutex when destroying

CHANGELOG.md, lib/vmpooler/pool_manager.rb
This commit updates destroy_vm to remove the redis member from the completed queue only after a destroy has been completed. Without this change a VM that is being destroyed will be logged as discovered when inventory is checked since it has already been removed from the completed queue.
=> Remove VM from completed only after destroy

CHANGELOG.md, Gemfile, PROVIDER_API.md, lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers.rb, lib/vmpooler/providers/dummy.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb, spec/unit/providers/base_spec.rb, spec/unit/providers/dummy_spec.rb, spec/unit/providers/vsphere_spec.rb, spec/unit/providers_spec.rb
This extends #181 by making it easier to load providers.
I am just throwing this up here for initial review.  There are no unit tests at this point but there are also other things that need to be added before this can be merged.  
What this code does is find all gems with providers in 'lib/vmpooler/providers' directories from all gems and loads any file found in that directory. This allows anyone to simply install a new provider gem and start using right away.   I would prefer that we only load the provider that is needed instead of everything.  However, more work will need to be done.   This will make it dead simple to start using external providers since all this is required is too have it installed.  This allows anyone to create a provider and keep separate from main gem.
Currently …
=> Adds a new mechanism to load providers from any gem or file path automatically

CHANGELOG.md, README.md, docker/Dockerfile, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb, vmpooler.yaml.dummy-example, vmpooler.yaml.example
This commit refactorss the check_pool method in pool_manager.
Specifically, each commented section describing a stage of check_pool is
broken out into a separate method and check_pool is simplified by
calling these methods. Without this change it is difficult to follow the
intent for or make changes to check_pool.
Additionally, a docker-compose file is added to make it simple to launch
an all-in-one vmpooler instance along with a separate redis server with
docker.
=> (POOLER-114) Refactor check_pool in pool_manager

CHANGELOG.md, lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb, spec/integration/api/v1/vm_template_spec.rb
This commit updates fetch_single_vm to return the name of the template that was requested, instead of the name of the pool providing the VM to meet the request. Without this change, when an alias is used for fetching a VM, a different pool title may be returned containing the requested VMs than the user initially requested.
=> (POOLER-131) Return requested name when getting VMs

CHANGELOG.md, lib/vmpooler/api.rb, lib/vmpooler/api/v1.rb
This commit updates the dashboard for vmpooler to ensure it is synchronized with any redis based configuration values before displaying the dashboard. Without this change the pool size value may be displayed incorrectly if the value has been set via the /config/poolsize API endpoint.
=> (POOLER-132) Sync pool size on dashboard start

CHANGELOG.md, docker/docker-compose.yml, docs/dev-setup.md, examples/vmpooler.yaml.dummy-example.aliasedpools, lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, spec/fixtures/vmpooler.yaml, spec/fixtures/vmpooler2.yaml, spec/unit/pool_manager_spec.rb, vmpooler.yaml.dummy-example, vmpooler.yaml.example
This commit fixes checking of a VM that has already been identified as ready. Without this change a ready VM that has failed will be identified as having failed, but will not successfully be removed from the ready queue. Additionally, the default vm_checktime value has been reduced from 15 to 1 to ensure that ready VMs are checked within one minute of the time they have reached the ready state by default.
Lastly, the docker-compose files are updated to specify that the redis
instance used is a local redis instance.
=> (POOLER-133) Identify when a ready VM has failed

CHANGELOG.md, docs/configuration.md, lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, spec/helpers.rb, spec/unit/pool_manager_spec.rb, spec/unit/providers_spec.rb, vmpooler.yaml.example
This commit updates vmpooler to ship VM usage stats when a VM is destroyed. The stats are gathered for jobs based on user and pool name. If a jenkins build URL is present then this is broken down by user, instance, value stream, branch and project. Additionally, if present then the RMM_COMPONENT_TO_TEST_NAME will be listed after project. Without this change we do not collect stats on per VM usage and its correlation to users and pools.
=> (POOLER-134) Ship VM usage stats

CHANGELOG.md, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates vm usage stats collection to replace all instances of '.' characters within node strings. Without this change the node string containing a '.' character causes the metric to be interpreted as containing another node.
=> Ensure nodes are consistent for usage stats

.travis.yml
This commit updates travis to test latest ruby versions for vmpooler. Without this change we test out of date versions of ruby with vmpooler.
=> (MAINT) Update travis to test latest ruby

.travis.yml
This commit updates travis configuration to stop testing 2.3.x and jruby 9.1.x. Without this change tests fail due to library incompatibilities with ruby 2.3.x.
=> Stop testing ruby 2.3.x

CHANGELOG.md, Gemfile, docs/configuration.md, lib/vmpooler.rb, spec/unit/env_config.rb
This commit updates vmpooler to set configuration values received via environment variables to integer values when an integer value is expected. Without this change vmpooler does not support setting integer values via environment variables. Additionally, testing is added for configuring vmpooler via environment variables.
To support this testing the gem climate_control is added, which allows
for testing environment variables without those set variables leaking to
other tests.
=> (POOLER-137) Support integer environment variables

docker/Dockerfile, docker/Dockerfile-aio, docker/Dockerfile_local
This commit updates jruby in dockerfiles from 9.1 to 9.2. Without this change the dockerfiles use a version of ruby that is no longer tested with vmpooler.
=> Update dockerfile jruby to 9.2

.travis.yml, CHANGELOG.md, lib/vmpooler.rb, lib/vmpooler/api/v1.rb, spec/helpers.rb, spec/integration/api/v1/config_spec.rb, spec/integration/api/v1/status_spec.rb, spec/integration/api/v1/vm_hostname_spec.rb, spec/integration/api/v1/vm_spec.rb, spec/integration/api/v1/vm_template_spec.rb, spec/integration/dashboard_spec.rb
This change updates handling of pool aliases to allow for more than a
single pool to be configured as an alias pool. Without this change if
multiple pools are configured as an alias the last one to configure it
is set as the alias for that pool.
Additionally, redis testing requirements are removed in favor of
mock_redis. Without this change a redis server is required to run
vmpooler tests.
=> (POOLER-138) Support multiple pools per alias

CHANGELOG.md, docker/Dockerfile, lib/vmpooler/api/v1.rb
This commit updates how vmpooler retrieves VMs to add a VM to the running queue as soon as it is checked out. Without this change it is possible that a VM can be discovered when it is checked out before it is added to the running queue if multiple systems are requested. Additionally, the dockerfile is updated to support specifying the version of vmpooler to install.
=> (POOLER-139) Fix discovering checked out VM

README.md, vmpooler.yaml.dummy-example
This pull request fixes up a dead link in the README to the Dockerfile, and also leaves a note in the dummy example config about making HTTP requests locally.
=> Fix Dockerfile link in readme and add note about http requests for dev

lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb
This commit updates how a VM is checked out to ensure that there is no window where the VM could be considered discovered, and therefore destroyed. Without this change the VM is retrieved by calling 'spop' on the ready queue, and then adding it to the running queue. This change moves to selecting the VM by retrieving the last member of the set, and moving it with 'smove' from ready to running. As a result of this change vmpooler moves from retrieving the VMs from the ready state randomly, to instead retrieve the oldest VM in the queue. This change should reduce churn where it would otherwise not be required to satisfy demand.
=> (POOLER-140) Ensure a running VM stays in a queue

docker/Dockerfile_local
This commit adds bundler to dockerfile_local in order to support building vmpooler. Without this change the dockerfile_local build fails reporting bundler is not available.
=> (MAINT) Add bundler to dockerfile_local

docs/API.md, lib/vmpooler/api/v1.rb, spec/integration/api/v1/status_spec.rb
Before this change we used the API /status endpoint to get specific information
on pools such as the number of ready VMs and the max.
This commit creates two new endpoints to get to that information much quicker
1) poolstat?pool= takes a comma separated list of pools to return, and will provide
the max, ready and alias values.
2) /totalrunning will calculate the total number of running VMs across all pools
It also uses the redis pipeline mode to speed up the DB requests.
=> (QENG-7201) Vmpooler pool statistic endpoint optimization

lib/vmpooler/pool_manager.rb
This commit updates how migrating and pending queues are processed. Sets to be processed are created with sadd in redis, and iterated over as a list in ruby. The latest member is added to the beginning of this set in redis, and becomes the first member of the set in ruby. To ensure that items are processed in the order they are added it is necessary to reverse the list before iterating through its members. Without this change the newest members of the set are processed first, which creates inconsistent times to evaluation.
=> (POOLER-141) Fix order of processing migrating and pending queues

docker/Dockerfile_local, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb, spec/integration/api/v1/vm_template_spec.rb
This commit duplicates the vm_ready? check to the API layer to allow for API to validate that a VM is alive at checkout. Without this change API relies upon the checks in pool_manager validating pools. This change should allow for additional insight into whether a machine is in a ready state and resopnding at checkout time.
=> (POOLER-140) Ensure a VM is alive at checkout

CHANGELOG.md, lib/vmpooler/api/v1.rb
This commit updates the reference to domain from vmpooler config. Without this change the domain value is read as an empty string and breaks checkouts.
=> (POOLER-140) Fix typo in domain

CHANGELOG.md, docker/Dockerfile_local, docs/configuration.md, lib/vmpooler.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/env_config.rb, spec/unit/providers/vsphere_spec.rb, vmpooler.yaml.example
This commit adds a new configuration parameter to allow setting whether to create linked clones on a global, or per pool basis. Without this change vmpooler would always attempt to create linked clones. The default behavior of creating linked clones is preserved.
=> Make it possible to disable linked clones

CHANGELOG.md, docs/API.md, lib/vmpooler/api/v1.rb, lib/vmpooler/providers/vsphere.rb, spec/helpers.rb, spec/integration/api/v1/vm_spec.rb, spec/unit/providers/vsphere_spec.rb
This change adds the running host for a VM to the API data available via /vm/hostname. Without this change the running host would be logged to vmpooler log, but not available any other way. Additionally, the data will specify if a machine has been migrated. Without this change parent host data for a vmpooler machine is not available via the vmpooler API.
=> (POOLER-142) Add running host to vm API data

CHANGELOG.md, lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
This commit updates the create_linked_clone pool option to correctly detect when linked clones have been set at a pool level. Without this change a pool setting create_linked_clone to false is not interpreted correctly, and a linked clone is created if possible.
=> (POOLER-147) Fix create_linked_clone pool option

lib/vmpooler/pool_manager.rb
The host['boottime'] variable in the function _check_ready_vm no longer
has its parent object in reference due to the refactoring in pull
request #269.  So in order to get the same information without the
performance impact from duplicate object lookups, we get similar
information from the time that the VM is ready.
=> (POOLER-148) Fix undefined variable bug in _check_ready_vm.

CHANGELOG.md, bin/vmpooler, lib/vmpooler/api.rb, lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb, spec/integration/api/v1/vm_template_spec.rb
This commit adds a shared mutex to vmpooler API so that checkout requests can be synchronized across threads. Without this change it is possible in some scenarios for vmpooler to allocate the same SUT to different API requests for a VM.
=> (POOLER-150) Synchronize checkout operations for API

bin/vmpooler, lib/vmpooler/api.rb
This commit updates the way that checkoutlock is defined so it is not passed through bin/vmpooler. Without this change there's an unnecessary layer the mutex passes through.
=> Simplify declaration of checkoutlock mutex

Gemfile, lib/vmpooler/pool_manager.rb
Prior to this commit hostnames for VMs provisioned by vmpooler were 15
random characters. This is difficult for humans to tell apart.
This commit updates the naming to use the `spicy-proton` gem to generate
adjective noun pair names for the VMs, which I think would be easier for
humans to tell apart, as well as fun and memorable to say.
=> (QENG-7530) Make VM names more human readable

Gemfile, vmpooler.gemspec
This commit adds the spicy-proton gem to vmpooler.gemspec. Without this change the spicy-proton gem is in the Gemfile, but not the gemspec, causing issues when deploying from gem.
=> Add spicy-proton to vmpooler.gemspec

lib/vmpooler/api/helpers.rb, spec/unit/api/helpers_spec.rb
Prior to this commit the hostname_shorten regex wouldn't match the
updated human readable hostnames because they contain dashes.
This commit updates the regex to capture dashes in the hostname.
=> (QENG-7530) Fix hostname_shorten regex

.rubocop.yml, .rubocop_todo.yml
Previously, there were some rubocop rule names that were causing rubocop
to fail to run entirely.
This commit updates the rubocop configs to match the new rubocop rule
names so that we can see all the issues that need correcting.
=> Update rubocop configs

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Prior to this commit the pooler had no awareness of the complete set of
hostnames that are currently in use. This meant that it was possible to
allocate the same hostname twice, which would result in the original
host with that hostname becoming unreachable.
This commit adds a check for the existence of the
`vmpooler__vm__<hostname>` key before attempting to  clone the vm.
This should prevent duplicate hostnames.
If the hostname is already taken, `_clone_vm` will retry with a new
random hostname multiple times before raising an exception.
=> (QENG-7530) Add check for unique hostnames

CHANGELOG.md
This commit updates the CHANGELOG, and fixes some Markdown linter issues
with the CHANGELOG.
=> Update CHANGELOG for 0.8.2

docker/docker-compose.yml, lib/vmpooler/api/v1.rb, spec/helpers.rb, spec/integration/api/v1/vm_hostname_spec.rb, vmpooler.yaml.example
Before this change, we could checkout a vm and set the lifetime to a
very high number which would esssentially keep the vm running forever.
Now implementing a config setting max_lifetime_upper_limit which enforces
a maximum lifetime in hours both for initial checkout and extending a
running vm
=> (POOLER-123) Implement a max TTL

lib/vmpooler/pool_manager.rb
This is a useful measure for monitoring the health of pools that we don't capture yet.
=> (QENG-7531) Add Marked as Failed Stat

lib/vmpooler/providers/vsphere.rb, spec/rbvmomi_helper.rb, spec/unit/providers/vsphere_spec.rb
Search the root and any subfolders for cluster or host resources.
This addresses issue #205
=> Support nested host folders in find_cluster()

lib/vmpooler/pool_manager.rb
Previously, we restricted the adjective and noun portion of the name
each to 7 characters to ensure that the final name would not be more
than 15 after adding a hyphen. Given that the _total_ length is what
matters, we now generate a noun up to 11 characters (to ensure we leave
room for a hyphen and a 3-letter adjective) and adjust our acceptable
adjective size accordingly. This lets many more names be generated than
would otherwise, while still respecting the 15 character limit.
We favor generating longer nouns rather than longer adjectives (by
selecting the noun first) because longer adjectives tend to be more
unwieldy words, and thus more awkward to say and generally less fun.
=> Generate a wider set of legal names

.travis.yml, docs/API.md, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, spec/integration/api/v1/poolreset.rb, spec/unit/pool_manager_spec.rb
This commit adds a capability to vmpooler to reset a pool, deleting its ready and pending instances and replacing them with fresh ones. Without this change vmpooler does not offer a mechanism to reset a pool without also changing its template.
=> (POOLER-153) Add endpoint for resetting a pool

lib/vmpooler/providers/vsphere.rb
Prior to this commit the vsphere migration code updated the redis value
for where the VM is running (`vmpooler__vm__#{vm_name}/host`) before
attempting the migration. This meant that if the migration failed, there
was no record of what the original host for the VM was. Additionally,
the VM was marked as migrated before the migration happened which
didn't reflect reality if the migration failed.
This commit moves the redis update during migration to after the
migration has completed. This means that if an exception is thrown in
the migration code, the original host won't be lost and the host won't
be considered as migrated when it was not.
=> (POOLER-154) Delay vm host update until after migration completes

CHANGELOG.md, docs/configuration.md, lib/vmpooler.rb, spec/unit/env_config.rb, vmpooler.yaml.example
This commit adds the extra_config option to vmpooler to allow specifying additional configuration files to load from. Without this change vmpooler does not offer a mechanism to provide additional configuration files for the application.
=> (POOLER-157) Add extra_config option to vmpooler

docker/Dockerfile, docker/Dockerfile-aio, docker/Dockerfile_local
This commit pins all the `Dockerfile` to Jruby 9.2.9. This is an
attempt to narrow down if the JRuby 9.2.11 is the reason for the
StackOverflow we were seeing or if there is something strange going on
with an update to the Gemfiles.
=> Pin to JRuby 9.2.9 in Dockerfiles

.rubocop.yml, .travis.yml, lib/vmpooler.rb, lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/logger.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
This should fix the remaining Rubocop issues that couldn't be autocorrected.
Still working on the last couple of issues, I'll remove the DNM tag when those are finished.
=> Manual Rubocop Fixes

docker/docker-compose.yml, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit adds detection for redis connection failures to pool_manager. When a connection fails the error will be raised to executeforcing the connection to be re-established. Without this change, when a redis connection fails, it generates a redis connection error, which is swallowed by a rescue for StandardError, preventing the manager application component from recovering in the case of a redis connection failure.
=> (POOLER-156) Detect redis connection failures

lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/vsphere.rb, spec/unit/pool_manager_spec.rb
This commit fixes the purge_unconfigured_folders feature to ensure that it can successfully identify folders and instances that are no longer used. Without this change the feature does not work as advertised.
=> (POOLER-165) Fix purge_unconfigured_folders

lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_hostname_spec.rb
Before this PR, the current running time was being inspected to decide if the
vm lifetime could be extended. But since vm lifetime is absolute and not relative
this check is now removed.
=> (POOLER-161) Fix extending vm lifetime when max lifetime is set

lib/vmpooler/api/v1.rb
Before this change if the smove returned false, we would continue handing out the VM
which presumably could still be in the 'ready' state. Upon 'delete' that ready VM would not be
picked up and return a 404 which is consistent with the behavior seen. Adding a metric to keep
track of the smove failures since this is not expected. I think some API logging would be good
to add in the future.
=> (DIO-608) vmpooler SUT handed out multiple times

lib/vmpooler/api/helpers.rb, spec/unit/api/helpers_spec.rb
This commit enables vmpooler to support an array of ldap user objects for authentication. This will allow us to also be able to authenticate requests through ldap service accounts.
=> (POOLER-171) Enable support for multiple user objects

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Before this change we checked that the new vm name would not conflict with an existing vm already running and under the vmpooler management in redis.
We now also check if a DNS query returns an existing IP, which could happen if there are stale DNS record (or some other process registered the vm name already, like another vmpooler?). In that case we skip that name and try again.
=> (POOLER-166) Check for stale dns records

lib/vmpooler/pool_manager.rb
It seems like generate_and_check_hostname does not need a method argument
this was fixed in one PR, and another change made in another PR and was used
inconsistently
=> (maint) Fix merge issue

lib/vmpooler/graphite.rb
This commit updates vmpooler graphite stats behavior when a connection cannot be opened to the graphite server to warn instead of allowing the full backtrace to be output to stderr. Without this change a backtrace is output to stderr when a graphite connection fails.
=> Rescue and warn when graphite connection cannot be opened

lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/util/parsing.rb, spec/unit/pool_manager_spec.rb
added leftover suggestions from #375
refactored every parsing of request of type 'pool_alias:pool:count' into a
utility class, that is used by pool_manager and the api v1 class
added metrics to the ondemand request generation
=> (POOLER-174) Reduce duplicate of on demand code introduced in POOLER-158

lib/vmpooler/providers/vsphere.rb, spec/rbvmomi_helper.rb, spec/unit/providers/vsphere_spec.rb
These changes check if a pool's configuration contains a `network` property. If so, at clone time, a vm's network device is reconfigured to the denoted network. 
It is necessary to reconfigure the network device since all vm templates are set up to connect to network `vmpooler`.
The `create_relocate_spec` and `create_clone_spec` methods were also created to break up the work performed in the `create_vm` method.
=> (POOLER-167) Allow for network configuration at vm clone time

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit updates folder purging references to ensure that provider
name references are referring to the named provider, rather than the
provider type. Without this change folder purging fails because it
cannot identify target folders.
=> Fix vmpooler folder purging

lib/vmpooler/api.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/metrics/promstats.rb, spec/unit/promstats_spec.rb, vmpooler.yaml.example
Introducing the Prometheus Stats code into ABS showed that the Clarity
could be improved a bit with better variable naming, some refactoring
to reduce repitition and documenting the Metrics table itself.
Filtering these changes back to the vmpooler code base.
=> (MAINT) Clarity refactor of Prom Stats code

lib/vmpooler/api/v1.rb, spec/integration/api/v1/ondemandvm_spec.rb
This change fixes template alias evaluation to ensure that the correct
data is set when generating on demand requests for pools that have a
backend weight configured for a value of 0. Without this change vmpooler
will return an empty selection in api for template alias evaluation.
To support this change tests are added that first reproduced the
failure, and then verified that it is resolved with the addition of the
patch. Additionally, test coverage is added to ensure that code paths
that include pickup gem usage are covered.
=> (POOLER-186) Fix template alias evaluation with backend weight of 0

lib/vmpooler/metrics/promstats.rb, spec/unit/promstats_spec.rb
This PR will allow us to get an exception raised with a helpful error message in case a metric is added and a component that utilizes it is not properly specified on the metrics table. A similar change was also implemented for ABS.
=> (maint) Add promstats component check

bin/vmpooler, lib/vmpooler.rb, spec/unit/generic_connection_pool_spec.rb, vmpooler.yaml.example
Adding a reconnect retry for redis, which by default would retry 10 times,
for a total wait time of ~80 seconds
=> (POOLER-184) Pool manager retry and exit on failure

.travis.yml
This change updates vmpooler to test ruby 2.5.8, and jruby 9.2.12.0. Without this change vmpooler tests against 2.5.7 and jruby 9.2.9.0. Additionally, testing on 2.4.x is removed. Lastly, rubocop tests are updated to run on 2.5.8.
=> Test vmpooler on latest 2.5

Gemfile, Vagrantfile, bin/vmpooler, docker/Dockerfile_local, docker/docker-compose.yml, lib/vmpooler.rb
This change utilizes OpenTelemetry's automatic instrumentation to add distributed tracing capabilities to VMPooler. This is a non-breaking change as traces are processed in noop mode by default.
=> Add distributed tracing

vmpooler.gemspec
This is to pull in the bug fix in https://github.com/open-telemetry/opentelemetry-ruby/pull/434 so that the new feature of naming spans based on their Sinatra route actually works.
=> Bump OTel Sinatra to 0.7.1

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This change adds detection of running instances that are in a running
queue, but have no data in a active queue for the same pool. When this
happens a machine will live forever, impacting the running count, and
preventing the machine from being killed. Without this change running
instances that are not marked as active will live forever.
=> (POOLER-191) Add checking for running instances that are not in active

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb, vmpooler.yaml.example
I've tested this locally and it appears to put the setting in the VMs vmx file at clone time
```
cat thin-precipice.vmx | grep mainM
mainMem.ioBlockPages = "2048"
mainMem.iowait = "0"
```
Tested by adding the following last two keys to the pool definition:
```
:pools:
- name: 'erik-testing'
snapshot_mainMem_ioBlockPages: '2048'
snapshot_mainMem_iowait: '0'
```
=> (DIO-1059) Optionally add snapshot tuning params at clone time

lib/vmpooler/api/helpers.rb, vmpooler.gemspec
While looking at the instrumentation data for the ABS queue processor,
I noticed a lot of time spent in the HTTP PUT method, which in the code
was easy to isolate, as it is only used via the vmpooler tagging functions
ie the API /vm/foobar/ with 'tag' key-value pairs.
While I'm not sure the original hset() make sense to me, there was an easy
way to speed them up by using pipelined. I would expect a very good speed
increase with this turned on.
=> (maint) Speedup the tagging method

lib/vmpooler/api/v1.rb
Checkout metric counters were against the template name and not the
actual pool used which prevents us from counting the checkouts in the
pixa4 pools for example.
This replaces #433 which was on a fork and therefore fails testing.
=> (MAINT) Fix checkout counter allocation

lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb
This change sets a VM as running in redis as soon as it is checked out. Without this change when allocated several instances it is possible for a machine that has been allocated for a checkout, but not yet marked as active, to be identified as running when it should not be, which was added in POOLER-191. Without this change a machine may be destroyed during checkout by pool_manager if there are several instances being allocated.
Additionally, redis multi is added for vm checkout operations to minimize the round trips to redis during a checkout operation. Without this addition each VM checkout causes several redis interactions.
=> (POOLER-193) Mark checked out VM as active

lib/vmpooler/api/v1.rb
This change removes usage of redis multi from API. Without this change the redis usage can cause issues because no connection pool is used, so another worker may try to use the same backend object causing a failure.
=> Remove usage of redis multi from api

lib/vmpooler/metrics/promstats/collector_middleware.rb, spec/unit/collector_middleware_spec.rb
It appears we renamed `/ondemand/` to `/ondemandvm/` at some point and, as a result, have not been stripping hostnames from that endpoint's metrics. This has caused issues with metrics collection due a very high cardinality.
=> (DIO-1503) Fix regex for ondemand instances

lib/vmpooler.rb, lib/vmpooler/api/helpers.rb, spec/unit/api/helpers_spec.rb, vmpooler.yaml.example
Prior to this, the encryption settings for LDAP auth were hard coded to start_tls on port 389 with TLSv1. These are still the defaults, as insecure as they are, so as to not break existing users. This change facilitates replacing the defaults so that simple_tls over port 636 via TLS1.2 can be used.
=> (DIO-2621) Make LDAP encryption configurable

docker/Dockerfile_local, docs/API.md, lib/vmpooler.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, spec/integration/api/v1/config_spec.rb, spec/unit/pool_manager_spec.rb, spec/unit/vmpooler_spec.rb
This implements a delete method for pooltemplate and poolsize. The API removes the override from Redis and then adds an entry in Redis that causes the pool manager to wake up and process the removal of the override.
To facilitate this, a new variable has been created in lib/vmpooler.rb to hold a copy of the original / pre-override config. This supplemental copy of the pools is then indexed for use as a reference.
When pool manager wakes up to process an override removal, it looks up the pre-override value from the config via the new variables mentioned above.
Just as with entering overrides, no restart is needed. Template and pool size changes are logged so that anyone watching or reviewing the logs can see what happened when. The new API endpoints also return values for both the …
=> (DIO-2675) Undo pool size & template overrides

docs/configuration.md, lib/vmpooler.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/base.rb, lib/vmpooler/version.rb, spec/unit/env_config.rb, spec/unit/pool_manager_spec.rb, vmpooler.yaml.example
vmpooler has the vsphere provider taken out, moving some vsphere related
methods to the provider:
1) pool_folders
2) get_base_folders
At the same time renaming some configuration and code items
to remove harmful terminology.
purge_unconfigured_folders DEPRECATED, use purge_unconfigured_resources
folder_whitelist DEPRECATED, use resources_allowlist
the above configuration items are still supported but will be removed in
the next major version.
base class method purge_unconfigured_folders was renamed to purge_unconfigured_resources
and requires the equivalent change in the provider classes
=> Move vsphere specific methods out of vmpooler

lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/base.rb, spec/unit/pool_manager_spec.rb
This method should be called only once, when the VM is moved to a running state
which is when the data for the user (if using tokens) is available. In vmpooler
base provider it is a noop method, but the various providers can implement it
to tag or label a running VM with the name of the user who checked it out
=> (maint) Adding a provider method tag_vm_user

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Prior to this, providers that should have been loaded per the provider_class key of the providers hash were not actually loaded.
=> Ensure all configured providers are loaded

lib/vmpooler.rb, lib/vmpooler/providers/base.rb, spec/fixtures/extra_config1.yaml, spec/fixtures/extra_config2.yaml, spec/unit/vmpooler_spec.rb, vmpooler.gemspec
Before this change if an extra config file had new keys they would get
merged to the main config but if it contained an existing key, like
'providers' it would overwrite the original config.
Adding a library 'deep_merge' to do a more natural merge, where existing keys
get sub-elements added together and arrays are combined like for the
pool configuration.
Adding spec tests around EXTRA_CONFIG as they were missing, by adding
and testing two new extra_config.yaml fixture files
=> (maint) Fix EXTRA_CONFIG merge behavior

lib/vmpooler/api/helpers.rb, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
The syntax for pipelined has changed and the old syntax will be removed in v5.0.0
Fixing the syntax now since the block syntax has been supported for a while now.
=> (maint) Fix deprecation warning for redis ruby library

.github/workflows/release.yml, .github/workflows/testing.yml, .github_changelog_generator, CHANGELOG.md, README.md, update-changelog, update-gemfile-lock
- Add the next version of jruby to testing (9.4)
- Update the gem release workflow
- Update changelog with changelog generator config
- Add/update scripts for updating the changelog and `Gemfile.lock`
- Add instructions for releasing
=> Add docs and update actions

.github/workflows/release.yml, .github/workflows/testing.yml, release-prep, update-gemfile-lock
Changelog: https://www.jruby.org/2023/03/08/jruby-9-4-2-0.html
ruby output difference:
```shell
> docker run --rm -it jruby:9.4.1.0-jdk11 bash -c 'ruby -v'
jruby 9.4.1.0 (3.1.0) 2023-02-07 237d5fa5f4 OpenJDK 64-Bit Server VM 11.0.18+10 on 11.0.18+10 +jit [x86_64-linux]
> docker run --rm -it jruby:9.4.2.0-jdk11 bash -c 'ruby -v'
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 11.0.18+10 on 11.0.18+10 +jit [x86_64-linux]
```
=> Bump jruby to 9.4.2.0

Gemfile.lock, docs/configuration.md, lib/vmpooler/api/helpers.rb, spec/unit/api/helpers_spec.rb, vmpooler.yaml.example
Fixes https://github.com/puppetlabs/vmpooler/issues/616
This retains backwards compatibility with existing ldap configurations.
=> (RE-15565) Add ability to use bind_as with a service account
