lib/vmpooler/api.rb
Add an endpoint that returns clone totals and average clone time for
the given time spans. The time spans are determined by the query
parameters "from" and "to", with the resulting range being inclusive of
both. If you want a single day, it should be both the "from" and the
"to" value.
=> Add /summary endpoint

lib/vmpooler/api.rb
- set proper HTTP status codes
- move 'content_type :json' to the beginning of endpoint defs
- deprecate 'Hash.new' for '{}'
=> Set HTTP status codes, a bit of code standardization

lib/vmpooler/api/v1.rb
This PR moves common metrics calculations to helpers.
=> Metric calc via helpers

lib/vmpooler/api/v1.rb
=> (maint) Fixing spacing

lib/vmpooler/api/v1.rb
This relies upon #61 be merged in order to collect metrics.
=> Show boot metrics in /status and /summary endpoints

lib/vmpooler/api/dashboard.rb
This fixes a redis reference that was missed in a previous refactor.
=> (maint) Fix bad redis reference

README.md, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb, vmpooler.yaml.example
=> Add basic auth token functionality

lib/vmpooler/pool_manager.rb, spec/vmpooler/pool_manager_spec.rb
Add spec tests for pool_manager#check_running_vm. In the process of
writing these tests, the method was broken in to smaller methods for
testability reasons.
=> (QENG-2360) check_running_vm Spec Tests

lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb, vmpooler.yaml.example
- Allow for configurable 'allowed_tags' tag restrictions
- Skip empty tags
=> (QENG-2388) Tagging restrictions

Rakefile
Add a default task that calls test.
=> (QENG-2246) Add Default Rake Task

lib/vmpooler/pool_manager.rb, spec/vmpooler/pool_manager_spec.rb
Make a note in the logfile when a pool is detected to be empty.
Also:
- vmpooler__empty__<pool> Redis key to determine when to log
- lifetime/TTL checks moved to `_check_running_vm` method
- no longer pay attention to VMware-based 'host.runtime.bootTime'
This PR implements a bunch of other stuff to account for rspec testing:
- Thread creation and looping in `check_pool`
- Everything else in `_check_pool`
=> Log empty pools

scripts/create_template_deltas.rb
...just `create_template_deltas.rb` for now.
=> (maint) Additional utility and reporting scripts

lib/vmpooler/api/reroute.rb, lib/vmpooler/api/v1.rb, spec/vmpooler/api/v1_spec.rb
Add a `GET /api/v1/token` route, eg:
````
$ curl -X GET -u jdoe --url https://vmpooler/api/v1/token
Enter host password for user 'jdoe':
````
````json
{
"ok": "true",
"a9znth9dq01t416hrguu56ze37t790bl": {
"created": "2015-04-30 19:09:20 -0700"
},
"ikqe0mtk7zzzjljvbgxnocx8w1o9dc9n": {
"created": "2015-05-19 13:25:42 -0700"
}
}
````
=> User token list

LICENSE
=> Update license copyright

README.md
=> Add info about vmfloaty

lib/vmpooler/providers/vsphere.rb, spec/unit/providers/vsphere_spec.rb
Was just missing the word 'not'.
=> Fix typo in error message

lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
This commit implements a vm_mutex hash to allow synchronizing VM operations that should only happen once across threads. Without this change pool_manager will try to evaluate or destroy a VM multiple times, which results in an error being thrown by one of the destroy attempts as only one can succeed and a duplication of resources unnecessarily when there are no errors.
=> (POOLER-112) Ensure a VM is only destroyed once

lib/vmpooler/api/v1.rb, spec/integration/api/v1/vm_spec.rb
Reverts puppetlabs/vmpooler#276
=> Revert "(POOLER-81) Add time_remaining information"

.gitignore, Gemfile, lib/vmpooler/version.rb, vmpooler.gemspec
This adds a basic gemspec file where previously one did not exist.
There are some additional fields to fill in so please comment with what those should be.
=> Adds a gemspec file

docker/Dockerfile_local, docker/docker-compose.yml
This commit adds a docker-compose file and a dockerfile to build vmpooler and install it from source.
=> Add docker-compose and dockerfile to support it

CHANGELOG.md
This commit updates the version in changelog in preparation for a release.
=> Update changelog version in preparation for release

CHANGELOG.md
This commit updates changelog in preparation of the 0.2.3 release.
=> Update changelog for 0.2.3

CHANGELOG.md
This commit updates the changelog to change version 0.2.2 to 0.3.0. The changes implemented are not patches so should not be a z release.
=> Change version 0.2.2 to 0.3.0

CHANGELOG.md
This commit updates the changelog to version 0.5.1 in preparation for release.
=> Update changelog to 0.5.1

lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, spec/unit/api/helpers_spec.rb
Before this change looping over many pools would query the redis backend
for each pool, leading in slow response from the backend for configurations
with many pools (60+)
Changed the requests to use redis pipelines https://redis.io/topics/pipelining
This is supported since the beginning, so will not force any redis update for
users. The pipeline method runs the queries in batches and we need to loop
over the result and reduces the number of requests to redis by N=number of
pools in the configuration.
=> (maint) Optimize the status api using redis pipeline

lib/vmpooler/api/v1.rb, lib/vmpooler/pool_manager.rb, spec/integration/api/v1/config_spec.rb, spec/unit/pool_manager_spec.rb
This allows the user to change the cluster in which the targeted pool
will clone to. Upon configuration change, the thread will wake up and
execute the change within 1 second.
=> (POOLER-143) Add clone_target config change to API

.rubocop.yml, .rubocop_todo.yml, CHANGELOG.md, lib/vmpooler/version.rb
Updates for release 0.10.3, tagging will be handled by the job.
=> Release 0.10.3

bin/vmpooler, lib/vmpooler.rb, lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/dashboard.rb, lib/vmpooler/generic_connection_pool.rb, lib/vmpooler/graphite.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers.rb, lib/vmpooler/providers/base.rb, lib/vmpooler/providers/dummy.rb, lib/vmpooler/providers/vsphere.rb, lib/vmpooler/statsd.rb
Generated using `bundle exec rubocop --safe --auto-correct`
Oh and:
```20 files inspected, 427 offenses detected, 344 offenses corrected```
=> Fix Rubocop "safe" auto-corrections

bin/vmpooler, lib/vmpooler.rb, lib/vmpooler/api.rb, lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/reroute.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/dashboard.rb, lib/vmpooler/dummy_statsd.rb, lib/vmpooler/generic_connection_pool.rb, lib/vmpooler/graphite.rb, lib/vmpooler/logger.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers.rb, lib/vmpooler/providers/base.rb, lib/vmpooler/providers/dummy.rb, lib/vmpooler/providers/vsphere.rb, lib/vmpooler/statsd.rb, lib/vmpooler/version.rb
Adds the remaining "unsafe" fixes that aren't included in #359
On top of the changes from #359:
```20 files inspected, 151 offenses detected, 46 offenses corrected```
=> "Unsafe" rubocop fixes

CODEOWNERS
=> (MAINT) Update CODEOWNERS

lib/vmpooler/api/v1.rb
This commit updates the method used for chceking the status of an
ondemand request to ensure that if multiple aliases are used to fulfill
a request that they are correctly presented as a single pool again when
everything is ready. Without this change it is possible for only one
group of an aliased pool to show up in pending or completed requests.
=> Correctly handle multiple pools of same alias in ondemand checkout

Gemfile, lib/vmpooler.rb
Adding this should allow OpenTelemetry to detect information about our Kubernetes environment.
=> Add OTel resource detectors

Gemfile, vmpooler.gemspec
It seems I should have put these in vmpooler.gemspec instead of the Gemfile. Now I know :)
=> Fix mixup of gem placement.

docker/Dockerfile, docker/Dockerfile-aio
In a previous PR I added make to Dockerfiles_local but didn't realize it also needed to be in the other two Dockerfiles... this fixes that
=> Adding make to the other two Dockerfiles

.github/workflows/lightstep.yml, .lightstep.yml, vmpooler.gemspec
Adds the Lightstep Pre-Deploy check
=> (DIO-1065) Add lightstep gh action

lib/vmpooler.rb, lib/vmpooler/api/dashboard.rb, lib/vmpooler/api/helpers.rb, lib/vmpooler/api/v1.rb, lib/vmpooler/metrics/dummy_statsd.rb, lib/vmpooler/metrics/graphite.rb, lib/vmpooler/metrics/promstats.rb, lib/vmpooler/metrics/statsd.rb, lib/vmpooler/pool_manager.rb, lib/vmpooler/providers/dummy.rb, lib/vmpooler/providers/vsphere.rb, spec/rbvmomi_helper.rb, spec/unit/pool_manager_spec.rb, spec/unit/providers/vsphere_spec.rb, vmpooler.gemspec
Fixes errors resulting from using Rubocop's new stable version v1.0 and updates the gem.
=> (POOLER-192) Use Rubocop 1.0

lib/vmpooler/version.rb
=> Bump version to 2.2.0

.github/workflows/snyk.yml
Adds a Snyk monitor action and migrates it from the DIO to RE org.
=> Add Snyk action and Move to RE org

.github/workflows/release.yml, CHANGELOG.md, Gemfile.lock, lib/vmpooler/version.rb
Commenting out the release action changelog validation until the release-prep script and action is updated to include Jira issues as part of https://puppet.atlassian.net/browse/POOLER-227
=> 3.1.0 release prep

lib/vmpooler/pool_manager.rb
Fixes https://github.com/puppetlabs/vmpooler/issues/601
=> (RE-15692) Do not attempt loading DNS classes if none are defined

lib/vmpooler/api/helpers.rb, lib/vmpooler/pool_manager.rb, spec/unit/pool_manager_spec.rb
Fixes https://github.com/puppetlabs/vmpooler/issues/609
=> (POD-10) Log reason for failed VM checks.
